### ISSUE TITLE
GitLab Integration

### ISSUE THREAD

**Issue by halkosajtarevic** [oliverguenther/openproject-revisions_git#2]
Hi!

Is it possible to extend your plugin to work with GitLab too?

This would be very very very nice! :+1:

Thanks in advance!

Halko

**Comment by oliverguenther** [comment]
I have not used GitLab in any production setting and thus cannot say what is required to port the plugin to GitLab.

That being said, I have no plans to extend the plugin for GitLab.

**Comment by halkosajtarevic** [comment]
Hi Oliver!

Thanks for your fast reply!

GitLab offers a very good API for creation and update of git-repositories. It's OpenSource and very powerfull in my opinion.

Probably I'll try to do it on my own :+1: 

Thank you for your time!
