### ISSUE TITLE
Two Git Keys get the same identifier

### ISSUE THREAD

**Issue by JohnDoe42** [oliverguenther/openproject-revisions_git#21]
Add two different git keys with different titles and end up with two different fingerprints but the same identifierer <username>_1.pub

**Comment by oliverguenther** [comment]
Yeah, that's a detail that must be changed from the user perspective - thanks for spotting.
The identifier of the gitolite key is _always_ `<login>_<userid>.pub`, however as the user can specify multiple keys, they are saved using the [Gitolite 3 multi-key / location structure](http://gitolite.com/gitolite/basic-admin.html#multi-key). 

Thus, the alphanumeric title is used as the location (== directory name). 
I've changed the list and form to reflect the actual implementation (c.f., screenshot) in 0231f01

![bildschirmfoto 2015-01-27 um 11 02 27](https://cloud.githubusercontent.com/assets/459462/5916718/6f48fe80-a614-11e4-8e4c-fcc35823c7a5.png)
