### ISSUE TITLE
Permissions to delete SSH Key

### ISSUE THREAD

**Issue by JohnDoe42** [oliverguenther/openproject-revisions_git#23]
I might be wrong, but currently a developer is not able to delete his SSH Key. The devs have all permissions in the "project archive" box but always get a 404 when trying to delete a key.

**Comment by oliverguenther** [comment]
I got a 403 in my tests, which was due to the key owner not being set. This should be fixed in 9fe4344

**Comment by JohnDoe42** [comment]
Which permission do I need to delete? Just being the owner of the key?

**Comment by oliverguenther** [comment]
Yes, either that or admin permissions, c.f., https://github.com/oliverguenther/openproject-revisions_git/blob/9fe43442ce5da97995c1824718133df244f3b682/app/helpers/gitolite_public_keys_helper.rb#L25
