### ISSUE TITLE
Line-wrapping in source view

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#24]
The highlighted source view wraps lines in a strange way (line-breaks before comments, it seems); I am not sure if it is the issue of this plugin, of OP or of the highlighting component. These images compare the same code in the repository view and in gvim (which the correct representation):
![op-repo](https://cloud.githubusercontent.com/assets/1029876/7154721/29a19a9a-e359-11e4-8529-8f893102b960.png)
![gvim](https://cloud.githubusercontent.com/assets/1029876/7154723/304b4148-e359-11e4-9a5f-5857ffac0f7d.png)

**Comment by oliverguenther** [comment]
The plugin does not touch the file rendering of the repository contents. The rendered section you describe originates from the [repository/entry view](https://github.com/opf/openproject/blob/dev/app/views/repositories/entry.html.erb), which calls an instance of [CodeRay](http://coderay.rubychan.de/) in [common/_file](https://github.com/opf/openproject/blob/dev/app/views/common/_file.html.erb).

That being said, I also see those comment indents.
![coderay](https://cloud.githubusercontent.com/assets/459462/7156062/f90a6974-e363-11e4-9823-940442bfd8e2.png)

 They seem to stem from this CSS rule in the OP core here: https://github.com/opf/openproject/blob/dev/app/assets/stylesheets/content/work_package_details/_activities_tab.sass#L39-L42

**Comment by oliverguenther** [comment]
Not sure if this was one of your guys, but a bug report has been filed at https://community.openproject.org/work_packages/19638

**Comment by eudoxos** [comment]
It was not me, but nice co-incidence. Thanks, agree to close here.

**Comment by oliverguenther** [comment]
I've proposed a fix for this issue in the PR [fix/coderay-comment-indent](https://github.com/opf/openproject/pull/2829) over in opf/openproject.
