### ISSUE TITLE
Integration with non-local git repositories (GitHub/BitBucket)?

### ISSUE THREAD

**Issue by AnthonyMDev** [oliverguenther/openproject-revisions_git#26]
Does this plugin support integration with git repositories hosted through other git services? The Installation guide mentions using Gitolite, and it seems that it only works with locally hosted repositories. Is that correct?

Thank you!

**Comment by mabentwickeltsich** [comment]
@AnthonyMDev,

The plugin works only with local Git repositories hosted by Gitolite.
