### ISSUE TITLE
Feature: Copy/paste button on repository overview

### ISSUE THREAD

**Issue by linuxmail** [oliverguenther/openproject-revisions_git#27]
Actually the user gets a "stop/forbidden" overview icon, while holding the mouse cursor over the "Repository access links" field. It would be nice, if there is a button for copy the link and remove the "forbidden" icon.

**Comment by mabentwickeltsich** [comment]
@linuxmail,

The development of the plugin for OpenProject 4 has stopped; the issue will not be corrected.

This feature is already implemented in version 5 of the plugin.
