### ISSUE TITLE
openproject-4.2.x: add support

### ISSUE THREAD

**Issue by piwats** [oliverguenther/openproject-revisions_git#28]
It seems that the plugin is broken, at least if one regards the Gemfiles...

Will there be an update to support 4.2.x?

**Comment by oliverguenther** [comment]
Hi @piwats ,

The plugin does not natively support 4.2 at the moment, however I am working on compatibility with the next release of OpenProject 5.0, which comes with an extensive set of features regarding repository management, to which this plugin will adapt to.

**Comment by mabentwickeltsich** [comment]
Last version of the plugin supporting OpenProject 4 is commit [cc68e4a](https://github.com/oliverguenther/openproject-revisions_git/commit/cc68e4af905101c04521d9c11297702c2599e981) that can be found in branch [feature/gwdg](https://github.com/oliverguenther/openproject-revisions_git/commits/feature/gwdg). It includes features such as Deployment credentials, Post receive URLs, Repository mirrors and Git config keys.

Be aware that there may be bugs that will not be corrected for OpenProject 4 as the development focuses on versions 5 and up.
