### ISSUE TITLE
Support rails 5.x

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#32]
Hi, I tried to update to Openproject 6.1 now and it seems that this package requires rails (<5, >=4.0) while the rest moved to 5 already... Is there an easy fix for that? Thanks!

**Comment by eudoxos** [comment]
As an update, even if I run OP6.1 without this gitolite plugin, I get fatal error from the template engine - some way around that? :
```
F, [2017-03-22T15:38:41.005669 #5168] FATAL -- :   
F, [2017-03-22T15:38:41.005767 #5168] FATAL -- : ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'Repository::Gitolite'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Repository.inheritance_column to use another column for that information.):
F, [2017-03-22T15:38:41.006044 #5168] FATAL -- :     62:         </h2>
F, [2017-03-22T15:38:41.006078 #5168] FATAL -- :     63:       </div>
F, [2017-03-22T15:38:41.006106 #5168] FATAL -- :     64:     </noscript>
F, [2017-03-22T15:38:41.006134 #5168] FATAL -- :     65:     <% main_menu = render_main_menu(@project) %>
F, [2017-03-22T15:38:41.006161 #5168] FATAL -- :     66:     <% side_displayed = content_for?(:sidebar) || content_for?(:main_menu) || !main_menu.blank? %>
F, [2017-03-22T15:38:41.006189 #5168] FATAL -- :     67:     <% initial_classes = initial_menu_classes(side_displayed, show_decoration) %>
F, [2017-03-22T15:38:41.006216 #5168] FATAL -- :     68:     <div id="wrapper" style="<%= initial_menu_styles %>" class="<%= initial_classes %>"
F, [2017-03-22T15:38:41.006243 #5168] FATAL -- :   
F, [2017-03-22T15:38:41.006269 #5168] FATAL -- : config/initializers/menus.rb:266:in `block (2 levels) in <top (required)>'
F, [2017-03-22T15:38:41.006296 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:240:in `allowed_node?'
F, [2017-03-22T15:38:41.006323 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:207:in `block in menu_items_for'
F, [2017-03-22T15:38:41.006350 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:206:in `each'
F, [2017-03-22T15:38:41.006377 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:206:in `menu_items_for'
F, [2017-03-22T15:38:41.006403 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:81:in `render_menu'
F, [2017-03-22T15:38:41.006428 #5168] FATAL -- : lib/redmine/menu_manager/menu_helper.rb:46:in `render_main_menu'
F, [2017-03-22T15:38:41.006460 #5168] FATAL -- : app/views/layouts/base.html.erb:65:in `_app_views_layouts_base_html_erb___3855671643481284253_70044864171400'
F, [2017-03-22T15:38:41.006487 #5168] FATAL -- : app/middleware/reset_current_user.rb:47:in `call'


```

**Comment by oliverguenther** [comment]
The error you mention is caused by a subclass of `Repository` being tried to instantiate, for which no associated model has been found (as you started without the plugin).

I can't comment on the _current_ compatibility of this version with OpenProject 6.1. However, that being said, the OpenProject core team will soon (within the next weeks) provide compatibility with 6.1. using a version of this plugin (possibly an earlier state to reduce to amount of setup needed).

**Comment by mabentwickeltsich** [comment]
Soon I will be working on that too. But I have to fix one issue that breaks SmartHTTP from OP 5.0.15 to OP5.0.16. Then I will iniciate to port the plugin to OP6.

Regards
Luis

**Comment by eudoxos** [comment]
> Soon I will be working on that too. But I have to fix one issue that breaks SmartHTTP from OP 5.0.15 to OP5.0.16. Then I will iniciate to port the plugin to OP6.

Thanks, Luis. Please let me know whenever you have something. We are currently unable to access any project with repository; even if you have dysfunctional version (interface-wise) which will be able to render the project summary page and such, it is still better as we will be able to use the rest of OP. Oh those upgrades without checking compatibility first...

> the OpenProject core team will soon (within the next weeks) provide compatibility with 6.1. using a version of this plugin

Meaning gitolite will be integrated as first-class repository type? That would be a great news.

**Comment by mabentwickeltsich** [comment]
Already working on porting the plugin to OP 6.

**Comment by mabentwickeltsich** [comment]
Testing with OP 6.0 (still Rails 4), but having progress.

**Comment by mabentwickeltsich** [comment]
I got the plugin working with OP 6.1.5 (latest release). I will do some more testing and upload the new version in the next days.

**Comment by eudoxos** [comment]
Great, I am looking forward to it. Thanks!

**Comment by mabentwickeltsich** [comment]
Hey @eudoxos,

I have uploaded a new version of the plugin. Please, have a look, test it and let me know if you encounter any problem. Install it from branch [release/6.1](https://github.com/oliverguenther/openproject-revisions_git/tree/release/6.1).

There are a couple of new things you have to configure. Check [README.md](https://github.com/oliverguenther/openproject-revisions_git/blob/release/6.1/README.md), steps [1. Gemfile.plugins](https://github.com/oliverguenther/openproject-revisions_git/blob/release/6.1/README.md#1-gemfileplugins) and [4. Configuration of OpenProject](https://github.com/oliverguenther/openproject-revisions_git/blob/release/6.1/README.md#4-configuration-of-openproject) which have changed.

Cheers
Luis

**Comment by eudoxos** [comment]
Great, Luis! Everything I tested works smoothly. Thanks a lot. Good luck with the thesis.
