### ISSUE TITLE
Users not able to manage their own public keys

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#33]
As regular user (not OP administrator), it seems the "Public keys" entry is not shown in the users profile page, thus users are not able to manage their public keys - they have to rely on administrator to do so. Is that intentional or configurable? IIt used to be editable by users (perhaps 2 years back) IIRC.

I am running opneporject 6.1.5 with this plugin updated a few months ago.

http://imgur.com/a/b6QwK

**Comment by oliverguenther** [comment]
IIRC, the public keys entry was only shown when the user had any project membership with a repository access role. Maybe that's the case in your issue?

**Comment by eudoxos** [comment]
That other user is a member of the project which has the repository, so I can exclude that one. (As a side-note, I think users still should be able to manage keys even if not (yet) part of a project with repository, just for the sake of consistency)

**Comment by mabentwickeltsich** [comment]
Hi @eudoxos,

As @oliverguenther said, it is only visible when the user has a project membership. HOWEVER, this is something that you (as system admin) have to configure.

Go to Administration | Roles and permissions | Permissions report | Repository
Enable/disable the permissions for a particular Role.

This is a basic standard configuration:
![image](https://user-images.githubusercontent.com/14220547/29565051-a7a8f942-8744-11e7-99c3-e3df94ba9c2a.png)

Have a look at MEMBER and PROJECT ADMIN roles, those are the most important. You can add/remove permissions according to your needs. The user will manage his/her public keys in My account | Public keys.

Cheers
Luis

**Comment by eudoxos** [comment]
Hi Luis, very helpful, thanks. For some reason my installation diverged from the default so the user was not able to manage keys himself. Issue solved, thanks for your help!
