### ISSUE TITLE
any support for openproject 7.4.1

### ISSUE THREAD

**Issue by impoetk** [oliverguenther/openproject-revisions_git#34]
are the instructions the same and only using the Gemfile.custom with said gems?

**Comment by oliverguenther** [comment]
Hi @impoetk , a maintained version for 7.4.  (with a different feature set than this plugin) is available at https://github.com/opf/openproject-gitolite

**Comment by impoetk** [comment]
i can't open issues there, but this step is unclear
https://github.com/opf/openproject-gitolite#1-gemfileplugins

by packaged installation is this file the /opt/openproject/Gemfile.plugins ?

when i tried that openproject was not starting at all, also the file here is not empty has already some groups there, should i create a new group? add it to an existing one?

also some commands involving the  ~/ (home) directory are not working for packaged installation, since the home folder is not pointing to what i found out was the folder used by openproject: home is /home/openproject and the folder where the files mentioned actually are is /opt/openproject

also the manual for installing plugins in this link: https://www.openproject.org/download-and-installation/#customization states that plugins should be in Gemfile.custom

and the procedure to install them are in https://www.openproject.org/plugins/install-plugins-packaged/

is this compatible with this plugin?

another question is how can i unset this property
openproject config:set CUSTOM_PLUGIN_GEMFILE=/etc/openproject/Gemfile.custom

and a last question (i promise) is if the commant for the omni-auth (or something like that) is using git:// protocol to get the changes, is it possible to change somewhere the command to https?? my server is inside a corporate network and im having trouble with that protocol :(

**Comment by oliverguenther** [comment]
Hi @impoetk,

https://www.openproject.org/download-and-installation/#customization is the correct guide to place a plugin . 

Regarding your second question, yes that's possible with

```
git config --global url.https://github.com/.insteadOf git://github.com/
```

Best,
Oliver
