### ISSUE TITLE
Is this support OpenProject 4.0.1?

### ISSUE THREAD

**Issue by Leminity** [oliverguenther/openproject-revisions_git#4]
Hi.

I'm installing this plugin. ^^;

I installed OpenProject 4.0.1 used by Packager.io.(not manual install).

My Issue's occured exception.

I got error message when execute command 'RAILS_ENV~~ script/delayed_job start'

error message's
# 

RAILS_ENV=production script/delayed_job start

leminity@leminity-MicroServer:/opt/openproject$ RAILS_ENV=production script/delayed_job start
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /opt/openproject/config/application.rb:128: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
    config.assets.precompile.unshift -> (path) {
                                         ^
/opt/openproject/config/application.rb:128: syntax error, unexpected tLAMBEG, expecting keyword_end
/opt/openproject/config/application.rb:130: syntax error, unexpected '}', expecting keyword_end
/opt/openproject/config/application.rb:168: syntax error, unexpected keyword_do_block, expecting keyword_end
/opt/openproject/config/application.rb:183: syntax error, unexpected keyword_end, expecting $end
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /opt/openproject/config/environment.rb:32:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
#     from script/delayed_job:3:in `<main>'

is this supported OpenProject 4.0.1?

I'll wait your answer. thx. ^^

**Comment by oliverguenther** [comment]
The plugin works fine in any stable release since 4.x. Your issue seems to be related to a config-error in `application.rb`. You should try and lint your configuration, e.g., using http://www.yamllint.com/
