### ISSUE TITLE
Please update install docs

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#5]
Hi Oliver, I appreciate your work on this plugin. I stumbled into issues mentioned in #3 (your answers are helpful) and I would like to suggest that the install docs are expanded a little bit. I would suggest the following:
- "you have successfully cloned the gitolite-admin.git repository from the user running OpenProject." is rather a terse instruction. Mentioning `git clone git@localhost:gitolite-admin /home/openproject/gitolite-admin.git` would be definitely very helpful.
- check for the SSH transport support in rugged in the Config test (for me, unfamiliar with RoR, it was not obvious how to find out about ssh support, except by googling the error from logs later).
- the point `Add include 'openproject.conf'` is quite unclear to me -- where is that file? Do I just say include that, without that file even existing?

Cheers!

**Comment by oliverguenther** [comment]
Thanks for your feedback - Any suggestions (especially toward the documentation) are much appreciated. I've included the first and last point in 91bd572532baea02217db40b0d280c413c797073

As for the SSH-transport, I've no other way of testing the functionality other than the one linked in the readme: https://github.com/libgit2/rugged/issues/299. Making a note however to print a more helpful error message if the transport doesn't exist in rugged.
