### ISSUE TITLE
How to fix nonexisting repo where OP thinks the project has one?

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#6]
I created repository from the web UI while I still had an invalid configuration of the plugin. Now when I go to "repository" under the project, OP thinks there is already a repository, and returns Internal error with the following log:

<pre>
sudo call with 'git --git-dir repositories/val/roro.git -c core.quotepath=false -c log.decorate=no branch --no-color' returned exit 128. Error was: fatal: Not a git repository: 'repositories/val/roro.git'
</pre>

How can I fix that? I tried `Rescue / Resync all project` (no idea what it should do, but looked right to me) without any change. Can I just create an empty git repository by hand (`git init /var/liv/gitolite3/repositories/val/roro.git`) and it will all work? Thanks!

**Comment by oliverguenther** [comment]
If there was an error during the initial repository setup, it may cause the repository to be created in OpenProject, but fail during sync with Gitolite. I'll probably have the repository deleted upon setup errors.

In that case, the `<gitolite-admin.git>/conf/openproject.conf` is probably missing a `val/roro.git` entry.
To fix it, you may be able to repair it by deleting and recreating the project under Settings > Repository.

If that too yields an error, please paste the error / log output here.

**Comment by eudoxos** [comment]
It went fine, I thought at first you were suggesting to delete and recreate the whole project (there are data in it already); deleting and re-creating the repo worked just fine. Thanks!
