### ISSUE TITLE
Is it possible to show the repo URI to users?

### ISSUE THREAD

**Issue by eudoxos** [oliverguenther/openproject-revisions_git#7]
I am not sure if this goes to the plugin or to OP in general. I see the repository name (project/subproject) under project settings, but regular users don't have access there, so I need to communicate to them "by hand" how to connect (git@mydomain.eu:project/subproject). The Repository page under project shows files and revisions, but no the URI. Is it possible to change this somewhere? Thanks!

**Comment by oliverguenther** [comment]
Yes, this is definitely planned feature. I haven't implemented it in the plugin so far because the role of repositories within the OpenProject Core [is still open for discussion and subject to change](https://community.openproject.org/topics/1166) -- and I currently have to override internal behavior heavily on the project/settings/repository tab. Nonetheless, as I can't see the discussion moving forward at the moment, I'll implement the feature in the plugin for now.

**Comment by oliverguenther** [comment]
29a334b implements the clone URL using the absolute / explicit `ssh://<user>@<host>/<repo path>.git` format. I prefer it over the relative / implicit `<user>@<host>:<path>`, however we could make it configurable.

![git clone url](https://cloud.githubusercontent.com/assets/459462/5696490/c0e202de-99d3-11e4-808f-6612099b9cdf.png)

**Comment by eudoxos** [comment]
Hi Oliver, I appreciate the effort (really) but it is something else than what I meant. When I click on the Repository page in the project (_not_ in Project settings), the URL should be presented there -- so that project members (but not admins) can see how to clone the repo. Would that be something possible to do?

**Comment by oliverguenther** [comment]
My bad. I've added a repository link in the sidebar of the repository page with 72f2561

![repolink_](https://cloud.githubusercontent.com/assets/459462/5707613/74a8d188-9a8a-11e4-9c9c-b1d2c03a1805.png)

**Comment by eudoxos** [comment]
Nice, tnaks. The last detail: could it embed the server name in the access link as well? Either taken from OP config, or configurable by hand in plugin settings (in my case those are different: OP is at vserver pro.mydomain.eu and git is git@mydomain.eu - it is the same machine, so git@pro.mydomain.eu will work as well).

**Comment by oliverguenther** [comment]
Hi, that should work already. Check the Plugin config (Administration -> Plugins -> Revisions/Git (Settings) -> Access). There should be an `SSH Server Domain` which sets the checkout hostname.

**Comment by eudoxos** [comment]
Perfect!!
